apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: delivery
spec:
  description: Delivery applications
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
